### ISSUE TITLE
[epic] Scope and deploy signed PHAR

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#338]
This ticket is to track the process of developing the last major functionality for 0.9.0 - automatic scoping and deploying PHAR to Github Releases.

Also, I would like to discuss several points, feedback is much appreciated.

- [x] Add ability to create the PHAR using [Humbug Box](https://github.com/humbug/box) (`make build/bin/infection.phar`)
- [x] (done https://github.com/infection/infection/pull/342) Prefix PHAR with [PHP Scoper](https://github.com/humbug/php-scoper). See [this example](https://github.com/humbug/php-scoper/blob/master/fixtures/set020-infection/scoper.inc.php)
- [x] (done https://github.com/infection/infection/pull/342) Run e2e tests with PHAR 
- [x] (done https://github.com/infection/infection/pull/342) Think about what to do with private keys locally. Probably do [the same as PHP Scoper does](https://github.com/humbug/php-scoper/blob/master/Makefile#L271)
- [ ] (in progress https://github.com/infection/infection/pull/353) Automatically deploy PHAR and key to releases (tags) with singing (requires travis integration). [How to](https://medium.com/@tfidry/create-and-deploy-secure-phars-c5572f10b4dd)

--------

>  Run e2e tests with PHAR  

Is it ok if we run e2e tests under PHPUnit with raw code, and `./tests/e2e_tests` with the scoped PHAR?

> Automatically deploy it for releases (tags) with singing

Shoud we switch from OpenSSL to GPG? The only one reason I see is [Phive requires GPG](https://phar.io/howto/sign-and-upload-to-github.html), didn't do much research though

**Comment by BackEndTea** [comment]
>Prefix PHAR with [PHP Scoper](https://github.com/humbug/php-scoper). See [this example](https://github.com/humbug/php-scoper/blob/master/fixtures/set020-infection/scoper.inc.php)

One thing to note:
The following part is no longer relevant due to the bootstrap refactor.
```php
if ($filePath === realpath(__DIR__.'/vendor/infection/infection/app/bootstrap.php')) {
    return str_replace($prefix.'\INFECTION_COMPOSER_INSTALL;', 'INFECTION_COMPOSER_INSTALL;', $contents);
 }
```

Should we also start to define 'extension' points, and white list those from the scoping process?

**Comment by BackEndTea** [comment]
Played around with this a bit locally, something like this *should* do the trick
```
php-scoper.phar:
	wget https://github.com/humbug/php-scoper/releases/download/0.6.1/php-scoper.phar
	wget https://github.com/humbug/php-scoper/releases/download/0.6.1/php-scoper.phar.pubkey
	chmod a+x php-scoper.phar

.PHONY: scope

scope: php-scoper.phar box.phar
	composer install --no-dev
	rm -rf ./build/phar
	./php-scoper.phar add-prefix --output-dir=./build/phar --force --no-interaction --stop-on-failure -vvv
	composer --working-dir=./build/phar dump-autoload --no-dev -o
	php box.phar compile
```

**Comment by borNfreee** [comment]
I managed to generate scoped PHAR by Box itself. Diff for current master


```diff
diff --git a/box.json.dist b/box.json.dist
index 6f08677..085a03d 100644
--- a/box.json.dist
+++ b/box.json.dist
@@ -10,6 +10,7 @@
     "compression": "GZ",
     "compactors": [
         "Herrera\\Box\\Compactor\\Json",
-        "Herrera\\Box\\Compactor\\Php"
+        "Herrera\\Box\\Compactor\\Php",
+        "KevinGH\\Box\\Compactor\\PhpScoper"
     ]
 }
\ No newline at end of file
diff --git a/scoper.inc.php b/scoper.inc.php
index 8c9454c..df3447c 100644
--- a/scoper.inc.php
+++ b/scoper.inc.php
@@ -11,7 +11,7 @@ return [
     //
     // For more see: https://github.com/humbug/php-scoper#finders-and-paths
     'finders' => [
-        Finder::create()->files()->in(['src', 'app', 'bin']),
+        Finder::create()->files()->in(['src', 'bin']),
         Finder::create()
             ->files()
             ->ignoreVCS(true)

```

**Comment by BackEndTea** [comment]
I'm not sure if it is relevant, but should we keep the `LICENSE` file in the phar?

**Comment by sanmai** [comment]
`./tests/e2e_tests` should be run both with `bin/infection` and with a scoped PHAR not only because we could better catch regressions this way, but also because we still support installing with Composer.

**Comment by borNfreee** [comment]
> Should we also start to define 'extension' points, and white list those from the scoping process?

not yet. All extension points require analyzing.

I'm pretty sure we need to move all interfaces/abstract classes our consumers will implement to its own package according to the best practices of Package Design. So it's definitely a separate ticket.
